defaultContentLanguage = "en"

[module]
  [module.hugoVersion]
    min = "0.120.0"

[markup]
  [markup.highlight]
    style = 'catppuccin-latte'
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true

[params]
  theme = "sine-die"
  themeLink = "https://sinetris.github.io/sine-die/"

  tagline = "minimalist Hugo theme"
  description = "sine-die a minimalist Hugo theme"

  # Search UI
  showSearchUI = false

  # Author
  author = "Duilio Ruggiero"
  authorLink = "https://sinetris.info"

  # License
  license = "MIT"
  licenselink = "https://github.com/sinetris/sine-die/blob/main/LICENSE"
  showLicenseInFooter = true

  # Copyright
  copyrightStartYear = "2023"
