[module]
[module.hugoVersion]
min = "0.120.0"

[outputFormats]
[outputFormats.PRINT]
name = "PRINT"
baseName = "index.print"
isHTML = true
mediaType = 'text/html'
permalinkable = false
noUgly = true

[outputFormats.SEARCH]
name = "SEARCH"
baseName = "index.search"
isPlainText = true
mediaType = 'text/javascript'
permalinkable = false
noUgly = true

[outputFormats.SERCHPAGE]
name = "SEARCHPAGE"
baseName = "search"
isHTML = true
mediaType = 'text/html'
permalinkable = false
noUgly = true


[params]
theme = "sine-die"
themeLink = "https://github.com/sinetris/sine-die"

description = """\
  sine-die a semantic HTML theme for Hugo
  """

# Search UI
showSearchUI = false

# Author
author = "Duilio Ruggiero"
authorLink = "https://github.com/sinetris"

# License
license = "MIT"
licenselink = "https://github.com/sinetris/sine-die/blob/main/LICENSE"
showLicenseInFooter = true

# Copyright
copyrightStartYear = "2023"
