name = "sine-die"
license = "MIT"
licenselink = "https://github.com/sinetris/sine-die/blob/master/LICENSE"
description = "Semantic HTML theme for Hugo"
homepage = "https://github.com/sinetris/sine-die"
demosite = "https://sinetris.github.io/sine-die/"
tags = [
  "accessibility friendly",
  "customizable palette",
  "dark mode",
  "docs",
  "minimal",
  "minimalist",
  "responsive",
  "search",
]
features = [
  "Accessibility frienly",
  "Breadcrumbs",
  "Customizable color palette",
  "Light/Dark mode",
  "Navigation Menubar",
  "Responsive Design",
  "Search functionality",
  "Semantic HTML",
  "Table of Contents",
]
min_version = "0.146.0"

[author]
name = "Duilio Ruggiero"
homepage = "https://sinetris.info"
