name = "Sine Die"
license = "MIT"
licenselink = "https://github.com/sinetris/sine-die/blob/master/LICENSE"
description = "Semantic HTML theme for Hugo"
homepage = "https://github.com/sinetris/sine-die"
tags = [
  "blog",
  "clean",
  "company",
  "customizable",
  "dark",
  "docs",
  "light",
  "minimal",
  "responsive",
  "search",
  "simple",
]
features = [
  "customizable",
  "dark-mode",
  "responsive",
  "search",
  "semantic-html",
]
min_version = "0.115.0"

[author]
name = "Duilio Ruggiero"
homepage = "https://github.com/sinetris"
