theme = "sine-die"
themesDir = "../.."
defaultContentLanguage = "en"
title = "sine-die"

[outputs]
  home = ["HTML", "RSS"]

[params]
  enableFavicons = true
  showSearchUI = true
  logo = "images/sine-die-logo.svg"
  # [params.logo]
  #   asset = "images/sine-die-logo.svg"
  #   imageTag = "img"
  #   [params.logo.attributes]
  #     fragment = "logo"
  #     viewBox = "0 0 1024 1024"

[markup]
  [markup.highlight]
    # We need classes to be able to have different colors for Light/Dark mode
    noClasses = false
    # We want line numbers to easily recognize line-wraps
    lineNos = true
    # Line wrapping don't work properly with line numbers in a separate table
    lineNumbersInTable = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true
