theme = "sine-die"
themesDir = "../.."
defaultContentLanguage = "en"
title = "sine-die"
sectionPagesMenu = 'main'

[outputs]
home = ["HTML", "RSS", "PRINT"]

[params]
subTitle = "A semantic HTML theme for Hugo"
contentSourceLink = "https://github.com/sinetris/sine-die"

description = """\
  sine-die minimalist CSS framework for Hugo example
  """

# Author
author = "Duilio Ruggiero"
authorLink = "https://github.com/sinetris"
