theme = "sine-die"
themesDir = "../.."
defaultContentLanguage = "en"
title = "sine-die"

[outputs]
home = ["HTML", "RSS", "PRINT"]

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'Palette'
  pageRef = '/pages/palette'
  weight = 20
[[menu.main]]
  name = 'Colors'
  pageRef = '/pages/colors'
  weight = 30
[[menu.main]]
  name = 'Components'
  pageRef = '/pages/components'
  weight = 40

[params]
contentSourceLink = "https://github.com/sinetris/sine-die"

description = """\
  sine-die minimalist CSS framework for Hugo example
  """

# Author
author = "Duilio Ruggiero"
authorLink = "https://github.com/sinetris"
