theme = "sine-die"
themesDir = "../.."
defaultContentLanguage = "en"
title = "sine-die"

[outputs]
  home = ["HTML", "RSS"]

[params]
  showSearchUI = true
  logo = "images/sine-die-logo.svg"

[markup]
  [markup.highlight]
    style = 'catppuccin-macchiato'
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true
